vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
       band_picture:
           uri_prefix: /images/band_picture
           upload_destination: '%kernel.project_dir%/public/images/band_picture'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
